dist: xenial
language: rust
addons:
  apt:
    packages:
      - libsystemd-dev
      - libdbus-1-dev
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo
install:
  - cargo install --force cargo-deb
script:
  - cargo build --verbose
  - cargo deb --verbose
